version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: no
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./make_tables.sql:/tmp/make_tables.sql # Available in container but NOT auto-run
      - ./load_data.sql:/tmp/load_data.sql # Available in container but NOT auto-run
      - ./data:/tmp/data
    networks:
      - db_network

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt_container
    environment:
      - DBT_PROFILE_DIR=/root/.dbt
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    depends_on:
      - postgres
    entrypoint: ['sh', '-c', 'dbt init novellia && tail -f /dev/null']
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - db_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  db_network: # Define the custom network
    driver: bridge
